[[bin]]
name = "python"
path = "src/python.rs"

[[bin]]
name = "pip"
path = "src/pip.rs"

[[bin]]
name = "snafu"
path = "src/snafu.rs"

[package]
name = "snafu-shims"
version = "0.0.0"

[dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2.8"
winreg = "0.4"
