image: Visual Studio 2017

max_jobs: 2

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      INSTALLER_ARCH: "amd64"
      RUST: x86_64-pc-windows-msvc
    - PYTHON: "C:\\Python36"
      INSTALLER_ARCH: "win32"
      RUST: i686-pc-windows-msvc

platform:
  - x86
  - x64

matrix:
  exclude:
    - platform: x86
      PYTHON: "C:\\Python36-x64"
    - platform: x64
      PYTHON: "C:\\Python36"

install:
  - "SET PATH=%PATH%;C:\\Program Files (x86)\\NSIS\\Bin"

  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - .\rustup-init.exe --default-host %RUST% --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check --upgrade pip"
  - "pip install --upgrade pipenv"
  - "pipenv install --system --dev --skip-lock"

  - "SET PATH"

build_script:
  - "for /f %%i in ('git describe') do @set SNAFU_GIT_VERSION=%%i"
  - "python .\\installers\\build.py %SNAFU_GIT_VERSION%"
  - "SET SNAFU_SETUP_EXE=snafu-setup-%INSTALLER_ARCH%-%SNAFU_GIT_VERSION%.exe"

test_script:
  - "flake8 ."
  - "pytest tests"

  - "docker build --build-arg SNAFU_SETUP_EXE=%SNAFU_SETUP_EXE% .\\installers"

artifacts:
  - path: ".\\installers\\%SNAFU_SETUP_EXE%"
